### ISSUE TITLE
create_admin_service.rb causes rake to fail because the confirm! method was removed from the Devise gem

### ISSUE THREAD

**Issue by tomelam** [RailsApps/rails-devise-roles#11]
See [the Devise changelog].(https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/CHANGELOG.md)

Rails Composer encounters this error when the rails-devise example app and its confirmable module are chosen:
    /Users/tom/.rvm/gems/ruby-2.3.3@rails426/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in \`method_missing'
    /Users/tom/Sites/mashweb.rails426-email-confirmable/app/services/create_admin_service.rb:6:in `block in call'
    /Users/tom/.rvm/gems/ruby-2.3.3@rails426/gems/activerecord-4.2.6/lib/active_record/core.rb:283:in 'initialize'
    /Users/tom/.rvm/gems/ruby-2.3.3@rails426/gems/devise-4.2.0/lib/devise/models/confirmable.rb:63:in 'initialize'

**Comment by tomelam** [comment]
I should have just linked to the [changelog in master](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md).
